# SPDX-FileCopyrightText: 2026 Mikhaeel Atef Rizk Wahba
# SPDX-License-Identifier: AGPL-3.0-or-later
"""SURFY surfaceome filter.

SURFY is a curated list of ~2,886 human surface proteins published by
Bausch-Fluck et al. (PNAS 2018). It's a high-confidence subset of the
predicted human surfaceome based on a machine-learned classifier trained on
mass-spec evidence.

Distribution: the full CC-BY list is **vendored** in
``bindsight/surfaceome/data/surfy_v1.uniprot.txt`` (2,886 accessions) and is
the authoritative source at query time. Discovery therefore needs no network
access for the surfaceome at all.

That is a deliberate change from lazy-fetching it on first use. The upstream
spreadsheet is no longer retrievable: ``wlab.ethz.ch`` serves an HTML landing
page (so ``pandas.read_excel`` died with ``BadZipFile``), and the relocated
``wollscheidlab.org`` serves a 132-byte Git-LFS pointer. Every fresh install
was therefore either hard-failing or silently degrading to a ten-protein list
and surfacing almost no candidates. Regenerate the vendored list with
``scripts/build_surfy_list.py``.

Resolution order at query time:

1. ``<user_cache>/bindsight/surfy/surfy_v1.uniprot.txt`` — a user-refreshed
   cache, if one exists, so a newer release can be adopted without upgrading.
2. The vendored full list — the normal path.
3. A ten-protein bundled fallback, used only when the first two are missing
   *and* the caller explicitly allows degraded results.
"""

from __future__ import annotations

import logging
from importlib import resources
from pathlib import Path

import requests
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from bindsight.io.paths import cache_dir

LOG = logging.getLogger(__name__)

# Number of proteins in the canonical SURFY list (Bausch-Fluck et al. 2018).
# Used as a sanity check after parsing.
SURFY_PROTEIN_COUNT = 2886

# Canonical SURFY surfaceome table (CC-BY), Bausch-Fluck et al. PNAS 2018.
#
# Retained for `populate_surfy_cache`, which is now an explicit opt-in refresh
# path rather than something the pipeline depends on. As of 2026-07 neither
# host serves the spreadsheet: the original returns an HTML landing page and
# the mirror returns a Git-LFS pointer. `load_surfy` uses the vendored list.
SURFY_XLSX_URL = "https://wollscheidlab.org/SURFY/table_S3_surfaceome.xlsx"

# The full vendored list, generated by scripts/build_surfy_list.py.
VENDORED_LIST_FILENAME = "surfy_v1.uniprot.txt"

# Bundled fallback for offline tests — a small set of well-characterized
# surface antigens. NOT a substitute for the full SURFY list in production.
_OFFLINE_FALLBACK_UNIPROT = frozenset(
    {
        "P04626",  # ERBB2 / HER2
        "P00533",  # EGFR
        "P56747",  # CLDN6
        "Q13421",  # MSLN (mesothelin)
        "P10747",  # CD28
        "P16410",  # CTLA-4
        "Q9NZQ7",  # PD-L1 / CD274
        "P09038",  # FGF2
        "P10275",  # AR
        "P19838",  # NF-kB1
    }
)


def _parse_accessions(text: str) -> frozenset[str]:
    """Parse one-accession-per-line text, ignoring comments and blanks."""
    return frozenset(
        line.strip() for line in text.splitlines() if line.strip() and not line.startswith("#")
    )


def _read_packaged(filename: str) -> str | None:
    """Read a data file shipped inside the package, or ``None`` if absent."""
    try:
        return resources.files("bindsight.surfaceome").joinpath("data", filename).read_text("utf-8")
    except (FileNotFoundError, ModuleNotFoundError, OSError):
        return None


def _bundled_uniprot_set() -> frozenset[str]:
    """Return the small offline-test surface-protein set bundled with bindsight."""
    text = _read_packaged("surfy_offline.txt")
    if text is None:
        return _OFFLINE_FALLBACK_UNIPROT
    return _parse_accessions(text)


def load_vendored_surfy() -> frozenset[str] | None:
    """Return the full vendored SURFY accession set, or ``None`` if unavailable.

    This is the canonical list shipped with the package — not a degraded
    fallback. It exists because the upstream spreadsheet is no longer
    retrievable; see the module docstring.

    Returns:
        The full accession set, or ``None`` when the data file is missing (for
        example in a trimmed-down install).
    """
    text = _read_packaged(VENDORED_LIST_FILENAME)
    if text is None:
        return None
    accessions = _parse_accessions(text)
    return accessions or None


def load_surfy(*, allow_offline_fallback: bool = True) -> frozenset[str]:
    """Return the set of UniProt accessions classified as surface by SURFY.

    Resolution order:

    1. ``<user_cache>/bindsight/surfy/surfy_v1.uniprot.txt`` — a refreshed cache,
       if the user populated one.
    2. The full vendored list shipped with the package (the normal path).
    3. The ten-protein bundled fallback.

    ``allow_offline_fallback`` gates **step 3 only**. Its purpose is to stop a
    run silently producing near-empty results from a ten-protein list; the
    vendored list is the real SURFY set and does not degrade anything, so it is
    always acceptable.

    Args:
        allow_offline_fallback: Permit the tiny bundled list when no full list
            is available.

    Returns:
        The set of surface-protein UniProt accessions.

    Raises:
        FileNotFoundError: No full list is available and the tiny fallback is
            not permitted.
    """
    cache_path = _surfy_cache_path()
    if cache_path.exists():
        cached = _parse_accessions(cache_path.read_text(encoding="utf-8"))
        if cached:
            return cached
        LOG.warning("SURFY cache at %s is empty; falling back to the vendored list", cache_path)

    vendored = load_vendored_surfy()
    if vendored is not None:
        LOG.debug("using vendored SURFY list (%d accessions)", len(vendored))
        return vendored

    if not allow_offline_fallback:
        raise FileNotFoundError(
            f"No full SURFY list available (cache: {cache_path}, vendored: "
            f"{VENDORED_LIST_FILENAME}). Reinstall bindsight, run "
            "scripts/build_surfy_list.py, or set allow_offline_fallback=True "
            "to accept the small bundled set."
        )

    LOG.warning(
        "Using small bundled offline SURFY fallback (%d proteins) — the full "
        "vendored list is missing from this install. Real discovery runs will "
        "surface almost nothing.",
        len(_bundled_uniprot_set()),
    )
    return _bundled_uniprot_set()


@retry(
    retry=retry_if_exception_type(requests.RequestException),
    wait=wait_exponential(multiplier=1, min=2, max=30),
    stop=stop_after_attempt(5),
    reraise=True,
)
def _download_xlsx(url: str) -> bytes:
    """Fetch the SURFY spreadsheet, verifying it really is one.

    Every other network client in the package retries; this one did not, and it
    also trusted a 200 response blindly. Both hosts now answer 200 with
    something that is not a spreadsheet — an HTML landing page and a Git-LFS
    pointer respectively — so the old code handed those bytes to openpyxl and
    surfaced ``BadZipFile: File is not a zip file``, which tells the user
    nothing about what actually went wrong.

    Args:
        url: Spreadsheet URL.

    Returns:
        The raw ``.xlsx`` bytes.

    Raises:
        RuntimeError: The response was not a spreadsheet.
    """
    resp = requests.get(url, timeout=120)
    resp.raise_for_status()
    content = resp.content

    # .xlsx is a zip container; anything else is an error page or a pointer.
    if not content.startswith(b"PK"):
        content_type = resp.headers.get("content-type", "unknown")
        if content.startswith(b"version https://git-lfs"):
            detail = "a Git-LFS pointer file, not the tracked content"
        elif b"<html" in content[:512].lower():
            detail = "an HTML page, not a spreadsheet"
        else:
            detail = f"{len(content)} bytes that are not a zip/xlsx container"
        raise RuntimeError(
            f"SURFY download from {url} returned {detail} "
            f"(content-type: {content_type}). Upstream has moved or is serving "
            "a placeholder. bindsight ships the full list already — "
            "load_surfy() does not need this download."
        )
    return content


def populate_surfy_cache(*, url: str = SURFY_XLSX_URL, force: bool = False) -> Path:
    """Refresh the on-disk SURFY cache from the upstream spreadsheet.

    **This is an opt-in refresh path, not a prerequisite.** :func:`load_surfy`
    reads the full vendored list and needs no network; call this only to adopt
    a newer upstream release without upgrading bindsight.

    As of 2026-07 neither known host serves the spreadsheet (one returns an
    HTML page, the other a Git-LFS pointer), so this will raise a descriptive
    ``RuntimeError``. Regenerating the vendored list with
    ``scripts/build_surfy_list.py`` is the supported route.

    Args:
        url: Spreadsheet URL to fetch.
        force: Re-download even when a cache already exists.

    Returns:
        Path to the populated cache file.

    Raises:
        RuntimeError: The download did not yield a spreadsheet, the ``discover``
            extra is missing, or the table parsed to zero surface proteins.
    """
    cache_path = _surfy_cache_path()
    if cache_path.exists() and not force:
        return cache_path

    try:
        import pandas as pd
    except ImportError as e:  # pragma: no cover - import guard
        raise RuntimeError(
            "populate_surfy_cache needs the 'discover' extra (pandas + openpyxl). "
            'Install with: pip install -e ".[discover]"'
        ) from e

    LOG.info("downloading SURFY surfaceome table from %s …", url)
    content = _download_xlsx(url)

    import io

    try:
        df = pd.read_excel(
            io.BytesIO(content),
            sheet_name="SurfaceomeMasterTable",
            header=1,
            engine="openpyxl",
        )
    except ImportError as e:  # pragma: no cover - import guard
        raise RuntimeError(
            "reading the SURFY .xlsx needs openpyxl (in the 'discover' extra). "
            'Install with: pip install -e ".[discover]"'
        ) from e

    label = df["Surfaceome Label"].astype(str).str.strip().str.lower()
    accessions = df.loc[label == "surface", "UniProt accession"].dropna().astype(str).str.strip()
    accs = sorted({a for a in accessions if a})
    if not accs:
        raise RuntimeError("parsed 0 surface proteins from SURFY table; format changed?")
    if len(accs) != SURFY_PROTEIN_COUNT:
        LOG.warning(
            "SURFY surface count %d != expected %d (upstream table may have been revised)",
            len(accs),
            SURFY_PROTEIN_COUNT,
        )

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_path.write_text(
        "# SURFY surfaceome (Bausch-Fluck et al., PNAS 2018; CC-BY).\n"
        f"# {len(accs)} UniProt accessions labelled 'surface'. Source: {url}\n"
        + "\n".join(accs)
        + "\n"
    )
    LOG.info("wrote %d surface accessions to %s", len(accs), cache_path)
    return cache_path


def is_surface_protein(uniprot_id: str, *, surfy: frozenset[str] | None = None) -> bool:
    """Return True if the UniProt accession is in the loaded SURFY set."""
    if surfy is None:
        surfy = load_surfy()
    return uniprot_id in surfy


def _surfy_cache_path() -> Path:
    return cache_dir("surfy") / "surfy_v1.uniprot.txt"
