# SPDX-FileCopyrightText: 2026 Mikhaeel Atef Rizk Wahba
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Guard the repository's public prose against regressing to overclaiming.

The v0.2.1 audit found six classes of defect in text that ships to readers
rather than to an interpreter: a superseded Zenodo *version* DOI cited in
seventeen places, a dead Boltz-2 reference in both bibliographies, a
deposit-ready preprint asserting the software is MIT-licensed when ``LICENSE``
is AGPL-3.0-or-later, an unqualified "the first open-source pipeline" priority
claim, binder-benchmark figures published without the protocol caveat they
need, and three release-metadata files disagreeing about the version number.

None of that is reachable by any other test in this suite, and every one of
those defects is a plain-text substring. These tests are therefore deliberately
string-level and data-driven: the file lists are module constants so a new
document is one line to cover, and the assertions name the exact bad string
that must stay gone and the exact good string that must stay present, so
rewording the surrounding sentence does not break them.

``CHANGELOG.md`` is intentionally outside :data:`PROSE_FILES`: it quotes the old
DOI and the retracted novelty claim verbatim while describing their removal.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]

# --- The exact strings the E-docs fixes turned on ----------------------------

# 10.5281/zenodo.20121496 is the v0.1.0 *version* DOI: an MIT-labelled snapshot
# with neither the benchmarks nor the manuscripts in it. ...495 is the concept
# DOI, which always redirects to the latest archived release.
STALE_VERSION_DOI = "10.5281/zenodo.20121496"
CONCEPT_DOI = "10.5281/zenodo.20121495"

# The Boltz-2 preprint DOI that returns HTTP 404, and the record it moved to.
DEAD_BOLTZ2_DOI = "10.1101/2025.01.20.633574"
LIVE_BOLTZ2_DOI = "10.1101/2025.06.14.659707"

# Licence claims that described bindsight itself as MIT. A bare "MIT" must
# survive in the manuscript: Boltz-2 / BoltzGen really did release weights
# under it, and scrubbing that attribution would be its own misstatement.
MIT_CLAIMS_ABOUT_BINDSIGHT = (
    "MIT-licensed and archived",
    "licensed MIT throughout",
    "(MIT license)",
)

# The retracted, unqualified priority claim, and the hedges that replaced it.
RETRACTED_NOVELTY_CLAIM = re.compile(r"first open[- ]source pipeline", re.IGNORECASE)
PRIORITY_CLAIM = re.compile(r"first open[- ]source", re.IGNORECASE)
NOVELTY_HEDGES = ("as far as we are aware", "to our knowledge")

# The designer benchmark. These constants used to enforce a caveat: the figures
# were produced with ProteinMPNN redesigning the target chain, so every document
# quoting them had to say so. A corrected re-run on a T4 has since superseded
# them, so what has to be enforced is the opposite — the documents must quote the
# corrected figures, and must not present the withdrawn ones as current.
MPNN_CHAIN_FLAG = "--pdb_path_chains"
#: The corrected figures. Any document that publishes the binder result states
#: at least one of them.
BINDER_FIGURES = re.compile(r"0\.88|40\s?%")
#: The withdrawn ones. Permitted only in a sentence that retracts them.
WITHDRAWN_BINDER_FIGURES = re.compile(r"0\.84|50\s?%\s*success|50%")
RETRACTION_WORDS = (
    "withdraw",
    "supersed",
    "earlier run",
    "superseded",
    "corrected",
    "no longer",
    "previous",
)

# --- The documents ------------------------------------------------------------

PROSE_SUFFIXES = frozenset({".md", ".tex", ".bib", ".cff"})
NAMED_PROSE = ("README.md", "SECURITY.md", "CITATION.cff", ".huggingface/README.md")
PROSE_TREES = ("docs", "paper", "benchmarks")

# One bibliography serves both manuscripts; manuscript.tex reaches it via
# \addbibresource{../paper.bib}. The former paper/biorxiv/references.bib
# duplicated 15 of its 18 keys and drifted independently.
BIB_FILES = ("paper/paper.bib",)
MANUSCRIPT_TEX = "paper/biorxiv/manuscript.tex"

# Documents that state, or used to state, a priority claim in prose.
PRIORITY_CLAIM_DOCS = (
    "README.md",
    "docs/index.md",
    "docs/what-is-bindsight.md",
    ".huggingface/README.md",
    "paper/paper.md",
    MANUSCRIPT_TEX,
)

# Documents that quote the pre-fix binder headline figures (ipTM 0.84 /
# 50% success@0.65) and must therefore carry the protocol caveat next to them.
#
# ``docs/results.md`` is generated byte-for-byte by
# ``scripts/build_docs_results.py`` (pinned by
# ``tests/test_docs_results.py::test_generated_page_is_up_to_date``), so the
# caveat has to come from the generator; regenerating the page cannot drop it
# without failing here.
BINDER_FIGURE_DOCS = (
    "README.md",
    "docs/index.md",
    "docs/results.md",
    "ARCHITECTURE.md",
    "CHANGELOG.md",
    "benchmarks/designer_benchmark/RESULTS.md",
    "benchmarks/designer_benchmark/DESIGNER_BENCHMARK.md",
)


def _collect_prose_files() -> list[Path]:
    """Every public text document, resolved from the trees above."""
    files = [ROOT / rel for rel in NAMED_PROSE]
    for tree in PROSE_TREES:
        files.extend(sorted(p for p in (ROOT / tree).rglob("*") if p.suffix in PROSE_SUFFIXES))
    return [p for p in files if p.is_file()]


PROSE_FILES = _collect_prose_files()
PROSE_IDS = [p.relative_to(ROOT).as_posix() for p in PROSE_FILES]


def _read(rel: str | Path) -> str:
    path = rel if isinstance(rel, Path) else ROOT / rel
    return path.read_text(encoding="utf-8")


def _bib_entry(text: str, key: str) -> str:
    """The body of a single BibTeX entry, so a field can be pinned to its key."""
    match = re.search(rf"@\w+\{{{re.escape(key)},(.*?)\n\}}", text, re.DOTALL)
    assert match is not None, f"bibliography entry {key} not found"
    return match.group(1)


# --- Inventory ----------------------------------------------------------------


def test_prose_inventory_resolves_the_public_documents() -> None:
    """Without this, a bad glob would make every scan below vacuously pass."""
    assert len(PROSE_FILES) >= 20
    for expected in (
        "README.md",
        "SECURITY.md",
        "CITATION.cff",
        ".huggingface/README.md",
        "docs/index.md",
        "docs/what-is-bindsight.md",
        "paper/paper.md",
        "paper/paper.bib",
        MANUSCRIPT_TEX,
        "benchmarks/designer_benchmark/RESULTS.md",
    ):
        assert expected in PROSE_IDS, f"not collected: {expected}"


# --- P5: the Zenodo DOI -------------------------------------------------------


@pytest.mark.parametrize("path", PROSE_FILES, ids=PROSE_IDS)
def test_no_public_document_cites_the_superseded_version_doi(path: Path) -> None:
    assert STALE_VERSION_DOI not in _read(path), (
        f"{path.relative_to(ROOT).as_posix()} still cites the v0.1.0 version DOI; "
        f"use the concept DOI {CONCEPT_DOI}"
    )


@pytest.mark.parametrize("rel", ["README.md", "CITATION.cff"])
def test_readme_and_citation_carry_the_concept_doi(rel: str) -> None:
    assert CONCEPT_DOI in _read(rel)


def test_citation_cff_declares_the_concept_doi_as_a_field() -> None:
    """GitHub's "Cite this repository" reads these keys, not the prose."""
    cff = yaml.safe_load(_read("CITATION.cff"))
    assert cff["doi"] == CONCEPT_DOI
    assert any(entry.get("value") == CONCEPT_DOI for entry in cff["identifiers"])


# --- I4: the bibliographies ---------------------------------------------------


@pytest.mark.parametrize("rel", BIB_FILES)
def test_bibliography_replaces_the_dead_boltz2_doi(rel: str) -> None:
    text = _read(rel)
    assert DEAD_BOLTZ2_DOI not in text, f"{rel} still cites the 404ing Boltz-2 DOI"
    assert LIVE_BOLTZ2_DOI in text


@pytest.mark.parametrize("rel", BIB_FILES)
def test_surfacebind_entry_is_balbi_2026(rel: str) -> None:
    """The SURFACE-Bind paper is Balbi et al. 2026, not Khakzad et al. 2025.

    Khakzad is a co-author, not the first author, and the article is dated
    2026. Pin both so the citation cannot drift back.
    """
    entry = _bib_entry(_read(rel), "Balbi2026")
    assert re.search(r"year\s*=\s*\{?\s*2026\s*\}?", entry), entry
    assert "Balbi" in entry, entry
    assert "Khakzad2025" not in _read(rel), "stale Khakzad2025 key still present"


# --- LEGAL: the licence of bindsight itself -----------------------------------


def test_manuscript_no_longer_calls_bindsight_mit_licensed() -> None:
    text = _read(MANUSCRIPT_TEX)
    for claim in MIT_CLAIMS_ABOUT_BINDSIGHT:
        assert claim not in text, f"manuscript still asserts {claim!r} about bindsight"
    assert "AGPL-3.0-or-later" in text


def test_manuscript_keeps_mit_only_as_an_upstream_attribution() -> None:
    """Boltz-2 / BoltzGen weights really are MIT; that sentence must survive.

    The invariant is not "no MIT" but "MIT never names bindsight".
    """
    mit_lines = [line for line in _read(MANUSCRIPT_TEX).splitlines() if "MIT" in line]
    assert mit_lines, "the upstream MIT attribution was scrubbed along with the overclaim"
    for line in mit_lines:
        assert "bindsight" not in line.lower(), line


# --- NOVELTY: the priority claim ----------------------------------------------


@pytest.mark.parametrize("rel", PRIORITY_CLAIM_DOCS)
def test_unqualified_priority_claim_is_gone(rel: str) -> None:
    assert not RETRACTED_NOVELTY_CLAIM.search(_read(rel)), (
        f"{rel} still makes the retracted 'first open-source pipeline' claim"
    )


@pytest.mark.parametrize("rel", PRIORITY_CLAIM_DOCS)
def test_every_surviving_priority_claim_is_hedged(rel: str) -> None:
    """A narrowed claim is still a priority claim; it must carry its qualifier."""
    text = _read(rel)
    for match in PRIORITY_CLAIM.finditer(text):
        window = text[max(0, match.start() - 400) : match.end() + 400].lower()
        assert any(hedge in window for hedge in NOVELTY_HEDGES), (
            f"{rel} claims priority at offset {match.start()} without a hedge"
        )


def test_readme_headline_hedges_the_priority_claim() -> None:
    """The hedge sits in the lede itself, not further down the page."""
    lede = "\n".join(_read("README.md").splitlines()[:12])
    assert "as far as we are aware, the first open-source tool" in lede
    assert "both halves end-to-end" in lede


# --- BINDER-BENCHMARK: provenance of the headline figures ---------------------


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_binder_figures_are_quoted_in_these_documents(rel: str) -> None:
    """Pins the list below to documents that really do publish the figures."""
    assert BINDER_FIGURES.search(_read(rel)), f"{rel} no longer quotes 0.88 / 40%"


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_the_withdrawn_figures_are_never_presented_as_current(rel: str) -> None:
    """ipTM 0.84 and 50% success@0.65 came from the pre-fix protocol.

    That run invoked ProteinMPNN without ``--pdb_path_chains``, so it redesigned
    the ERBB2 target chain along with the binder: the designs were optimised
    against a partly-invented surface and then scored against the native one. A
    corrected re-run on a T4 supersedes them.

    These tests used to enforce the caveat. Now they enforce the retraction: the
    old numbers may appear only in a sentence that withdraws them, because a
    document that prints both sets without saying which is current publishes two
    results.
    """
    text = _read(rel)
    for match in WITHDRAWN_BINDER_FIGURES.finditer(text):
        window = text[max(0, match.start() - 500) : match.end() + 500].lower()
        assert any(word in window for word in RETRACTION_WORDS), (
            f"{rel} prints a withdrawn binder figure at offset {match.start()} "
            "without retracting it"
        )


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_the_corrected_protocol_is_named_where_the_figures_appear(rel: str) -> None:
    """The claim that makes the new figures trustworthy must travel with them.

    "The target was held fixed" is the whole difference between this run and the
    superseded one, and it is checkable: every design carries a target chain
    byte-identical to the native domain IV.
    """
    text = _read(rel)
    assert MPNN_CHAIN_FLAG in text or "target chain" in text.lower(), (
        f"{rel} quotes the binder figures without saying the target was held fixed"
    )


# --- Release metadata coherence -----------------------------------------------


def test_version_agrees_across_pyproject_citation_and_zenodo() -> None:
    """``bindsight --version``, the citation and the deposit must not disagree."""
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]["version"]
    citation = str(yaml.safe_load(_read("CITATION.cff"))["version"])
    zenodo = json.loads(_read(".zenodo.json"))["version"].removeprefix("v")
    assert re.fullmatch(r"\d+\.\d+\.\d+", pyproject), pyproject
    assert citation == pyproject, f"CITATION.cff {citation} != pyproject {pyproject}"
    assert zenodo == pyproject, f".zenodo.json {zenodo} != pyproject {pyproject}"


#: ``bindsight --version`` shown with its output, e.g. in a fenced example:
#:     bindsight --version           # 0.2.2
#: Release notes elsewhere name old versions on purpose, so only text presented
#: as this command's own output is checked.
_DOCUMENTED_VERSION_OUTPUT = re.compile(r"bindsight\s+--version[^\n]*?#\s*v?(\d+\.\d+\.\d+)")


def _documents_showing_version_output() -> list[tuple[str, str]]:
    """Every (path, version) a shipped document presents as ``--version`` output."""
    return [
        (path.relative_to(ROOT).as_posix(), version)
        for path in _shipped_documents()
        for version in _DOCUMENTED_VERSION_OUTPUT.findall(path.read_text(encoding="utf-8"))
    ]


def test_the_sweep_for_documented_versions_still_finds_the_known_example() -> None:
    """Guards the guard: a pattern that matches nothing would make the check
    below vacuous, which is exactly how docs/how-to-use.md sat two releases behind."""
    shown = _documents_showing_version_output()
    assert (
        "docs/how-to-use.md",
        tomllib.loads(_read("pyproject.toml"))["project"]["version"],
    ) in shown, (
        f"the --version sweep no longer sees the docs/how-to-use.md example; it found {shown}"
    )


def test_documented_version_output_matches_the_package() -> None:
    """docs/how-to-use.md promised ``# 0.2.0`` while the package shipped 0.2.2.

    A reader runs the command and sees a different number than the page says --
    small, but it is the page telling them something untrue about the software.
    """
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]["version"]
    for rel, shown in _documents_showing_version_output():
        assert shown == pyproject, (
            f"{rel} shows `bindsight --version` printing {shown}; pyproject says {pyproject}"
        )


def test_licence_agrees_across_pyproject_citation_and_zenodo() -> None:
    """The v0.1.0 Zenodo record said MIT for AGPL code; that is what to prevent."""
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]["license"]
    citation = yaml.safe_load(_read("CITATION.cff"))["license"]
    zenodo = json.loads(_read(".zenodo.json"))["license"]
    assert pyproject == "AGPL-3.0-or-later"
    assert citation == pyproject
    assert zenodo == pyproject


# ---------------------------------------------------------------------------
# The manuscripts must not out-claim the README
# ---------------------------------------------------------------------------
#: Backends the README states have not been run end to end, with the words it
#: uses to say so. A manuscript may name them; it may not present them as
#: demonstrated.
UNEXECUTED_BACKENDS = ("Modal", "Colab")

#: Words that turn a mention into a disclosure rather than a claim.
_HEDGES = (
    "not been run",
    "not executed",
    "not yet",
    "prepared",
    "demonstration",
    # Not a bare "demo": the bioRxiv abstract's own paragraph says "A public web
    # demo", which satisfied the scan while the sentence beside it claimed four
    # backends run end to end. A hedge has to be the wording that actually
    # qualifies the claim, not any nearby occurrence of the word.
    "demonstration rather than",
    "demo, not",
    "needs a human",
    "does not permit",
    "cannot",
    "implemented but",
)

#: Every manuscript that ships. The bioRxiv .tex was missing from this list
#: while the same module already governed it for licence and priority claims,
#: and that is exactly where an unhedged four-backend claim survived — in the
#: abstract, the most-read sentence the project publishes.
MANUSCRIPTS = (
    "paper/paper.md",
    "paper/validation/manuscript.md",
    "paper/biorxiv/manuscript.tex",
)


@pytest.mark.parametrize("rel", MANUSCRIPTS)
@pytest.mark.parametrize("backend", UNEXECUTED_BACKENDS)
def test_no_manuscript_presents_an_unexecuted_backend_as_demonstrated(
    rel: str, backend: str
) -> None:
    """paper.md claimed the GPU half runs end-to-end on Colab, Modal and Docker.

    The README calls Modal "Prepared, not executed" and Colab "a demo, not a
    reproducibility path". Both documents shipped, contradicting each other,
    and nothing compared them — a reviewer reading the pair is the first person
    who would have.
    """
    path = ROOT / rel
    if not path.is_file():
        pytest.skip(f"{rel} not present")
    text = path.read_text(encoding="utf-8")
    # Scoped to the paragraph, not a character window: a qualification belongs
    # to the sentence it qualifies, and a fixed radius either clips a hedge that
    # is genuinely present or reaches into unrelated prose.
    for para in re.split(r"\n\s*\n", text):
        low = para.lower()
        if backend.lower() not in low or not re.search(r"end[- ]to[- ]end", low):
            continue
        assert any(h in low for h in _HEDGES), (
            f"{rel} presents {backend} as running end to end, but the README "
            f"states it has not been run that way. Paragraph:\n{para[:400]}"
        )


def test_the_readme_still_marks_those_backends_unexecuted() -> None:
    """If a backend is genuinely demonstrated, this pair of tests must be revised
    together rather than the manuscript quietly getting ahead of the evidence."""
    readme = _read("README.md").lower()
    assert "prepared, not executed" in readme
    assert "not a reproducibility path" in readme


#: Files that count tests per changeset rather than describing the suite. The
#: CHANGELOG says "15 tests" about one release's additions; that is history, not
#: a claim about how large the suite is now, and it must not be rewritten.
_TEST_COUNT_EXEMPT = {"CHANGELOG.md"}

#: Any shipped document that states a number of tests is claiming it about this
#: suite. Written as a pattern rather than a file list because the previous
#: version of this guard read only paper/paper.md, and paper/README.md sat at a
#: stale "635 tests" for as long as that list went unrevised.
_TEST_COUNT_CLAIM = re.compile(r"(over\s+)?(\d[\d,]*)\s+(?:\w+\s+){0,3}?tests\b", re.I)


def _shipped_documents() -> list[Path]:
    """``PROSE_FILES`` plus every root-level document.

    ``NAMED_PROSE`` lists four root files by hand and so misses ARCHITECTURE.md,
    CHANGELOG.md and anything added later -- the same shape of omission that let
    paper/README.md sit at a stale figure. Root markdown is discovered, not listed.
    """
    files = set(PROSE_FILES)
    files.update(q for q in ROOT.glob("*.md") if q.is_file())
    return sorted(files)


def _test_function_count() -> int:
    """A lower bound on collected cases: parametrised tests expand beyond this,
    so a claim that clears this number is true of the real suite too."""
    return sum(
        len(re.findall(r"^\s*(?:async )?def test_", p.read_text(encoding="utf-8"), re.M))
        for p in (ROOT / "tests").glob("*.py")
    )


def _documents_stating_a_test_count() -> list[tuple[str, bool, int]]:
    """Every (path, is_floor, count) test-size claim in a shipped document."""
    found: list[tuple[str, bool, int]] = []
    for path in _shipped_documents():
        rel = path.relative_to(ROOT).as_posix()
        if path.name in _TEST_COUNT_EXEMPT:
            continue
        for floor, number in _TEST_COUNT_CLAIM.findall(path.read_text(encoding="utf-8")):
            found.append((rel, bool(floor), int(number.replace(",", ""))))
    return found


def test_the_sweep_for_test_counts_still_finds_the_known_claims() -> None:
    """Guards the guard. A regex that silently stops matching would turn the
    check below into a test that passes because it inspects nothing."""
    claiming = {rel for rel, _floor, _n in _documents_stating_a_test_count()}
    assert "paper/paper.md" in claiming, (
        f"the test-count sweep no longer sees paper/paper.md; it found {claiming}"
    )
    assert "paper/README.md" in claiming, (
        f"the test-count sweep no longer sees paper/README.md; it found {claiming}"
    )


def test_no_shipped_document_claims_more_tests_than_the_suite_has() -> None:
    """The manuscript once claimed 635 tests against a suite of 784 functions;
    paper/README.md later claimed 635 against 1097. Both directions are wrong to
    ship, so every document is swept, not the one that was wrong last time.

    Counts must be stated as floors ("over N"). An exact number is a claim that
    goes stale the moment a test is added, which is how both figures rotted.
    """
    functions = _test_function_count()
    for rel, is_floor, claimed in _documents_stating_a_test_count():
        assert is_floor, (
            f"{rel} states an exact test count ({claimed}); write it as "
            f'"over N tests" so adding tests cannot make the document wrong'
        )
        assert claimed <= functions, (
            f"{rel} claims over {claimed} tests; only {functions} test functions exist"
        )


#: Designers and validators that no shipped backend can execute. The README's
#: runner-and-plugin table is the authority; these must never be ticked off as
#: delivered elsewhere.
UNEXECUTED_PLUGINS = ("BindCraft", "BoltzGen", "Chai-1r", "AF2-IG")


@pytest.mark.parametrize("plugin", UNEXECUTED_PLUGINS)
def test_no_completed_checklist_item_claims_an_unexecuted_plugin(plugin: str) -> None:
    """`- [x] design/ RFdiffusion+ProteinMPNN (+ BindCraft, BoltzGen)` read as
    delivered while the same document's table said those two had never run.

    A checklist is the fastest thing in a design document to scan and the
    easiest to leave behind, so the tick is the claim that matters.
    """
    # A tick about a plugin's *licence* or citation is not a delivery claim, and
    # confirming BindCraft's licence is genuinely done.
    not_about_running = ("licen", "cite", "citation", "attribut")
    for line in _read("ARCHITECTURE.md").splitlines():
        low = line.lower()
        if not line.lstrip().startswith("- [x]"):
            continue
        if any(word in low for word in not_about_running):
            continue
        assert plugin.lower() not in low, (
            f"ARCHITECTURE.md ticks off {plugin}, which no backend can run:\n{line}"
        )


def test_the_three_way_benchmark_is_not_claimed_as_a_mitigation_in_place() -> None:
    """It was written as a mitigation already taken; it is deferred work.

    BindCraft and BoltzGen have never executed, so a benchmark comparing all
    three designers cannot have been run.
    """
    text = _read("ARCHITECTURE.md").lower()
    assert "benchmark all three in the paper" not in text


def test_the_readme_still_marks_those_plugins_unexecuted() -> None:
    """The anchor for the two tests above: if this changes, revise them together.

    "implemented, not yet executed" was the original phrasing and was too kind —
    it implies the plugins would work if someone ran them, when no backend
    builds an environment in which the dispatch can succeed. Either wording
    keeps the manuscripts honest, which is what these tests are for.
    """
    readme = _read("README.md")
    assert any(
        phrase in readme
        for phrase in (
            "implemented, not yet executed",
            "not runnable",
            "no shipped backend can run them",
        )
    )


# ---------------------------------------------------------------------------
# The withdrawn success rate must not travel without its notice
# ---------------------------------------------------------------------------
#: Directories searched for documents stating the success@0.65 figure.
#:
#: Discovered, not listed. The first version of this guard was a hand-written
#: tuple of the files its author remembered, and it missed README.md and
#: docs/index.md — the two most-read surfaces in the repository, both
#: publishing the withdrawn rate as a headline. A guard that only checks the
#: files you thought of protects exactly the files you were already thinking
#: about.
#:
#: The rate itself is a real Boltz-2 output and is kept rather than deleted —
#: removing it would hide the finding instead of stating it. But a paired
#: control showed designs and shuffles of their own sequences clearing it at the
#: same rate, so it is not a measure of design quality, and a reader meeting the
#: number without that is misled by omission.
_SEARCH_ROOTS: tuple[str, ...] = (".", "docs", "benchmarks", "paper")

#: Substrings that identify a document stating the rate.
_SUCCESS_RATE_MARKERS: tuple[str, ...] = ("success@0.65", "success @ ipTM 0.65")

#: Paths excluded from the sweep, each for a stated reason.
_NOT_PUBLISHED: tuple[str, ...] = (
    "benchmarks/calibration/",  # the calibration itself; it *is* the withdrawal
    "runs/",  # run outputs, not shipped prose
    "site/",  # built output
    "node_modules/",
)


def _documents_stating_the_success_rate() -> list[str]:
    """Every shipped Markdown file that states the designer benchmark's rate."""
    root = Path(__file__).resolve().parents[1]
    found: set[str] = set()
    for sub in _SEARCH_ROOTS:
        base = root / sub
        if not base.is_dir():
            continue
        for path in base.rglob("*.md"):
            rel = path.relative_to(root).as_posix()
            if any(skip in rel for skip in _NOT_PUBLISHED):
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            if any(marker in text for marker in _SUCCESS_RATE_MARKERS):
                found.add(rel)
    return sorted(found)


SUCCESS_RATE_DOCUMENTS: tuple[str, ...] = tuple(_documents_stating_the_success_rate())

#: The phrase every one of them must carry.
WITHDRAWAL_MARKER = "withdrawn as a measure of design quality"


def _flat(text: str) -> str:
    """Collapse whitespace, so a wrapped sentence still matches.

    Markdown decides its own line breaks. A guard that misses the notice
    because a word moved to the next line reports a document as unprotected
    when it is protected — and, worse, invites whoever hits it to reword the
    notice until the substring matches again.
    """
    return " ".join(text.split())


@pytest.mark.parametrize("rel", SUCCESS_RATE_DOCUMENTS)
def test_every_document_quoting_the_success_rate_withdraws_it(rel: str) -> None:
    assert WITHDRAWAL_MARKER in _flat(_read(rel)), (
        f"{rel} states the success rate without the withdrawal notice; the rate "
        "is matched exactly by shuffles of the designs' own sequences"
    )


def test_the_sweep_actually_finds_the_documents() -> None:
    """A discovery that finds nothing would make every test above vacuous.

    This is the failure the hand-written list had in a quieter form: it passed
    while missing the two most-read files in the repository.
    """
    assert len(SUCCESS_RATE_DOCUMENTS) >= 5, SUCCESS_RATE_DOCUMENTS
    for expected in ("README.md", "ARCHITECTURE.md"):
        assert expected in SUCCESS_RATE_DOCUMENTS, (
            f"{expected} states the rate but the sweep did not find it"
        )


def test_the_notice_is_one_string_not_a_family_of_paraphrases() -> None:
    """Every surface renders the same text, so none of them can go stale alone."""
    from bindsight.benchmark.designer_bench import IPTM_CALIBRATION_CAVEAT

    assert WITHDRAWAL_MARKER in IPTM_CALIBRATION_CAVEAT
    # Discovered, not listed. The previous version of this named two files, and
    # two benchmark guides carrying the same notice in its superseded first-run
    # wording were outside its scope for as long as the list went unrevised.
    opening = IPTM_CALIBRATION_CAVEAT.strip().splitlines()[0]
    carriers = [
        path
        for path in _calibration_surfaces()
        if path.suffix == ".md" and opening[:60] in path.read_text(encoding="utf-8")
    ]
    assert len(carriers) >= 2, (
        f"expected the long-form notice on at least two surfaces; found {carriers}"
    )
    for path in carriers:
        rel = path.relative_to(ROOT).as_posix()
        assert IPTM_CALIBRATION_CAVEAT.strip() in path.read_text(encoding="utf-8"), (
            f"{rel} opens the notice but then paraphrases it instead of carrying it "
            "verbatim, so the two copies can drift"
        )


def test_the_notice_states_the_numbers_that_justify_it() -> None:
    """A withdrawal without its evidence is an assertion like the one it replaces."""
    from bindsight.benchmark.designer_bench import IPTM_CALIBRATION_CAVEAT

    for figure in ("50%", "30%", "−0.043", "0.40", "0.172", "0.139"):
        assert figure in IPTM_CALIBRATION_CAVEAT, f"the notice omits {figure}"
    assert "benchmarks/calibration" in IPTM_CALIBRATION_CAVEAT


def test_the_notice_matches_the_measured_artifact() -> None:
    """The quoted figures come from the calibration run, not from memory."""
    import json

    from bindsight.benchmark.designer_bench import IPTM_CALIBRATION_CAVEAT

    results = json.loads(_read("benchmarks/calibration/RESULTS.json"))
    assert f"{results['design_pass_rate']:.0%}" in IPTM_CALIBRATION_CAVEAT
    assert f"{results['scramble_pass_rate']:.0%}" in IPTM_CALIBRATION_CAVEAT
    # Rendered with a typographic minus, so compare on the digits.
    assert f"{abs(results['paired_difference']['mean']):.3f}" in IPTM_CALIBRATION_CAVEAT
    assert f"{results['exact_signflip_p']:.2f}" in IPTM_CALIBRATION_CAVEAT
    assert f"{results['refold_drift']['abs_delta']['median']:.3f}" in IPTM_CALIBRATION_CAVEAT
    assert f"{results['sampling_noise']['pooled_per_draw_sd']:.3f}" in IPTM_CALIBRATION_CAVEAT
    assert f"{results['variance_decomposition']['between_pair_share']:.0%}" in (
        IPTM_CALIBRATION_CAVEAT
    )


def test_the_report_surfaces_carry_the_withdrawal_too() -> None:
    """The rendered report is what a reader actually looks at.

    Guarding only the Markdown would leave the number standing unqualified on
    the one surface most people see, which is the opposite of the point.
    """
    import inspect

    from bindsight.report import showcase, webapp

    for module in (showcase, webapp):
        source = inspect.getsource(module)
        if "ipTM 0.65" not in source:
            continue
        assert "withdrawn" in source.lower(), (
            f"{module.__name__} renders the success rate without the withdrawal"
        )


def test_the_demo_help_does_not_promise_a_rediscovery_the_study_refutes() -> None:
    """``bindsight demo --help`` said it "rediscovers ERBB2 (HER2) and EGFR as
    top antibody-tractable surface antigens".

    The rediscovery study measures ERBB2 in a whole unstratified breast cohort
    below the fold-change floor, so it does not clear the significance rule, and
    the demo's own config comment says EGFR is often lower in bulk tumour than in
    normal breast. A help string is the first thing a new user reads; it is not
    the place to assert an outcome the repository's own artifact contradicts.
    """
    from bindsight.cli import demo

    help_text = " ".join((demo.__doc__ or "").split())
    assert help_text, "the demo command lost its help text"
    assert "rediscovers ERBB2" not in help_text, help_text
    assert "result, not a scripted one" in help_text, (
        "the demo help no longer says that which antigens surface is the run's "
        f"own result: {help_text}"
    )


# ---------------------------------------------------------------------------
# SURFY ships in the package; no document may say it is fetched
# ---------------------------------------------------------------------------
def test_the_vendored_surfaceome_is_actually_in_the_package() -> None:
    """The premise of the next test, checked rather than assumed."""
    vendored = ROOT / "bindsight" / "surfaceome" / "data" / "surfy_v1.uniprot.txt"
    assert vendored.is_file(), f"the vendored surfaceome is missing: {vendored}"
    accessions = [ln for ln in vendored.read_text(encoding="utf-8").splitlines() if ln.strip()]
    assert len(accessions) > 2000, (
        f"the vendored list holds {len(accessions)} accessions; the full SURFY list "
        "is ~2,886 and a short one is the degraded fallback"
    )


def test_no_document_says_the_surfaceome_is_downloaded_on_first_run() -> None:
    """docs/how-to-use.md listed SURFY under "on first real run these populate
    automatically", "downloaded from wlab.ethz.ch/surfaceome".

    The package vendors the list precisely because that download stopped working:
    the old host serves a landing page and the relocated one a Git-LFS pointer,
    so fetching it was either hard-failing or silently degrading to a ten-protein
    list. A reader following the page would wait for a fetch that never happens
    and, if it did, would get the wrong thing.
    """
    claims = []
    for path in _shipped_documents():
        rel = path.relative_to(ROOT).as_posix()
        if rel == "CHANGELOG.md":
            continue  # a historical record of when the fetch was removed
        for line in path.read_text(encoding="utf-8").splitlines():
            lowered = line.lower()
            if "surfy" not in lowered and "surfaceome" not in lowered:
                continue
            if any(word in lowered for word in ("download", "fetch")) and not any(
                word in lowered
                for word in ("vendored", "no longer", "not downloaded", "needs no network")
            ):
                claims.append(f"{rel}: {line.strip()}")
    assert not claims, "documents claiming the surfaceome is fetched:\n" + "\n".join(claims)


def test_the_success_card_states_its_count_and_interval() -> None:
    """The landing page showed "40%" with a withdrawal note and no interval,
    directly beside a card reading "1 of 17 ... 95% CI 0.01-0.27".

    The interval exists in the artifact (15%-70%, clustered over backbones) and
    ``DesignerShowcase.success_interval`` already said in its own docstring that
    a page printing the rate without it "claims a precision twenty designs from
    ten backbones do not carry". It simply was not read at this call site.
    """
    artifact = ROOT / "benchmarks" / "designer_benchmark" / "results.json"
    if not artifact.is_file():
        pytest.skip("designer benchmark artifact not present")
    designer = json.loads(artifact.read_text(encoding="utf-8"))["designers"][0]
    low = round(designer["success_ci_low"] * 100)
    high = round(designer["success_ci_high"] * 100)

    page = " ".join(_read("docs/index.md").split())
    start = page.index("success @ ipTM 0.65")
    card = page[start : start + 500]

    assert f"{designer['n_success']} of {designer['n_designs']}" in card, card[:400]
    assert str(low) in card, f"the card omits the lower bound {low}%: {card[:400]}"
    assert str(high) in card, f"the card omits the upper bound {high}%: {card[:400]}"


def test_the_generated_success_card_carries_the_same_interval() -> None:
    """The hand-written landing page and the generated card must not diverge."""
    from bindsight.report.showcase import headline_stats, load_designer_benchmark

    designer = load_designer_benchmark(ROOT / "benchmarks")
    if designer is None or designer.success_rate is None:
        pytest.skip("designer benchmark artifact not present")

    cards = [h for h in headline_stats() if "success" in h.label]
    assert cards, "the showcase no longer renders a success card"
    detail = cards[0].detail

    assert f"{designer.n_success} of {designer.n_designs}" in detail, detail
    assert "95%" in detail, detail
    assert "clustered over backbones" in detail, detail
    assert "withdrawn" in detail, detail


#: Designers the README states no shipped backend can execute. The three-way
#: designer benchmark cannot be completed on the free path at all, which is a
#: different statement from "not run yet".
_UNRUNNABLE_DESIGNERS = ("BindCraft", "BoltzGen")


@pytest.mark.parametrize("rel", MANUSCRIPTS)
def test_no_manuscript_says_the_three_way_benchmark_only_awaits_a_gpu(rel: str) -> None:
    """The bioRxiv draft said the benchmark ships "to be populated from a GPU run".

    Two things were wrong with that. One arm *is* populated — the
    RFdiffusion+ProteinMPNN figures the same paper reports come from a real
    Kaggle T4 run of that harness. And the other two are not merely waiting: the
    README says no shipped backend builds an environment in which BindCraft or
    BoltzGen executes, and that both need 24–32 GB against anything larger than a
    small domain, so the comparison needs paid hardware rather than more free
    tier. "Awaiting a GPU run" reads as a scheduling detail; it is a capability
    limit.
    """
    path = ROOT / rel
    if not path.is_file():
        pytest.skip(f"{rel} not present")
    text = " ".join(path.read_text(encoding="utf-8").split())
    if not any(name in text for name in _UNRUNNABLE_DESIGNERS):
        pytest.skip(f"{rel} does not discuss the designer benchmark")

    assert "to be populated from a GPU run" not in text, (
        f"{rel} presents the three-way benchmark as merely pending a GPU run"
    )


def test_the_readme_still_says_those_designers_need_paid_hardware() -> None:
    """The premise of the test above. If the README ever reports them running on
    free hardware, the manuscript wording must be revised with it rather than
    the pair silently disagreeing again."""
    readme = _read("README.md")
    assert "no shipped backend can run them" in readme, (
        "the README no longer says the alternative designers cannot run; revisit "
        "what the manuscripts say about the three-way benchmark"
    )
    assert "paid backends" in readme


def _success_interval_from_artifact() -> tuple[int, int] | None:
    """The benchmark's own 95% bounds, as whole percents."""
    artifact = ROOT / "benchmarks" / "designer_benchmark" / "results.json"
    if not artifact.is_file():
        return None
    designers = json.loads(artifact.read_text(encoding="utf-8")).get("designers") or []
    for entry in designers:
        low, high = entry.get("success_ci_low"), entry.get("success_ci_high")
        if low is not None and high is not None:
            return (round(low * 100), round(high * 100))
    return None


@pytest.mark.parametrize("rel", SUCCESS_RATE_DOCUMENTS)
def test_every_document_stating_the_rate_also_states_its_interval(rel: str) -> None:
    """The withdrawal notice was already required on every one of these. The
    interval was not, so eleven surfaces carried it and one did not — and the
    landing page showed a bare "40%" directly beside a card quoting a 95% CI.

    A point estimate over twenty designs from ten backbones resolves to steps of
    5%; printing it alone claims a precision the run does not have, withdrawal
    notice or no withdrawal notice.
    """
    bounds = _success_interval_from_artifact()
    if bounds is None:
        pytest.skip("designer benchmark artifact not present")
    low, high = bounds
    text = _flat(_read(rel))

    # CHANGELOG.md states what each release reported at the time; a dated entry
    # is a record, not a live claim, and back-filling today's interval into it
    # would falsify the record.
    if rel == "CHANGELOG.md":
        pytest.skip("dated historical entries, not a current claim")

    # The interval is required of a document that states the RATE, not of one
    # that only names the metric. Which is which is decided by the artifact's own
    # point estimate appearing in the text, not by a guess at sentence shape: an
    # earlier heuristic here skipped docs/index.md and docs/results.md, both of
    # which do state it, and so checked nothing on the two surfaces that matter
    # most.
    artifact = ROOT / "benchmarks" / "designer_benchmark" / "results.json"
    designer = json.loads(artifact.read_text(encoding="utf-8"))["designers"][0]
    point = f"{designer['success_rate']:.0%}"
    fraction = f"{designer['n_success']}/{designer['n_designs']}"
    spelled = f"{designer['n_success']} of {designer['n_designs']}"
    if not any(form in text for form in (point, fraction, spelled)):
        pytest.skip(f"{rel} names the metric without stating its rate")

    # Anchored to a percent sign. A bare "70" matched inside "−0.070" in a
    # neighbouring sentence, so RUN_ON_KAGGLE.md passed this check while stating
    # no interval at all -- the guard was reading a digit out of another number.
    bounds = re.compile(
        rf"\b{low}\s*(?:%|&ndash;|–|-|to)\s*{high}\s*%|\b{low}%\s*(?:–|-|to)\s*{high}%"
    )
    assert bounds.search(text), (
        f"{rel} states the success rate without the interval the artifact reports ({low}–{high}%)"
    )


# ---------------------------------------------------------------------------
# The superseded first calibration run must not be quoted as current
# ---------------------------------------------------------------------------
#: The first paired job ran an unseeded validator at one diffusion draw and found
#: designs and shuffles tied. The seeded re-run at five draws -- the committed
#: artifact -- found the shuffles ahead. These markers belong only to the first
#: run, and quoting them as the finding inverts the sign of a published result.
_SUPERSEDED_CALIBRATION: tuple[str, ...] = (
    "40% and 40%",
    "40% vs 40%",
    "paired difference +0.030",
    "difference was +0.030",
    "sign-flip p = 0.57",
    "p = 0.57",
    "median of 0.129",
)

#: Files allowed to quote the first run, each because it explicitly frames it as
#: the first run rather than the finding:
#:   CHANGELOG.md -- dated entries, a record of what was known when.
#:   benchmarks/calibration/README.md -- narrates the sequence, and puts these
#:     figures under "What happened: the first row of the table", followed by
#:     "The seeded re-run settled it".
_CALIBRATION_HISTORY_ALLOWED: frozenset[str] = frozenset(
    {"CHANGELOG.md", "benchmarks/calibration/README.md"}
)


def _calibration_surfaces() -> list[Path]:
    """Every place a reader can meet the calibration result.

    Prose *and* code: the superseded figures were also hard-coded into the
    Streamlit UI's tooltip, which no documentation sweep would ever have seen.
    """
    # ``tests`` is excluded because this module necessarily contains the
    # forbidden strings in order to forbid them; no test file is a surface a
    # reader of the project's results ever meets.
    skip = (".git", "site", "runs", "node_modules", "__pycache__", ".venv", "tests")
    out: list[Path] = []
    for path in ROOT.rglob("*"):
        if path.suffix not in {".md", ".tex", ".py"}:
            continue
        parts = set(path.relative_to(ROOT).parts)
        if parts & set(skip):
            continue
        out.append(path)
    return sorted(out)


def test_the_sweep_for_calibration_surfaces_sees_prose_and_code() -> None:
    """Guards the guard: a sweep that missed .py would have missed the UI copy."""
    found = {p.relative_to(ROOT).as_posix() for p in _calibration_surfaces()}

    assert "README.md" in found
    assert "bindsight/report/webapp.py" in found, (
        "the sweep no longer covers the Streamlit app, where a superseded copy of the notice lived"
    )
    assert "benchmarks/designer_benchmark/DESIGNER_BENCHMARK.md" in found


def test_no_surface_quotes_the_superseded_calibration_run_as_current() -> None:
    """The root README, ARCHITECTURE, two benchmark guides and the live web UI all
    told the reader designs and shuffles cleared 0.65 at the same rate. The
    committed artifact says the shuffles clear it more often. That is the sign of
    the result, not a detail.
    """
    offenders: list[str] = []
    for path in _calibration_surfaces():
        rel = path.relative_to(ROOT).as_posix()
        if rel in _CALIBRATION_HISTORY_ALLOWED:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for marker in _SUPERSEDED_CALIBRATION:
            if marker in text:
                offenders.append(f"{rel}: {marker!r}")
    assert not offenders, (
        "surfaces quoting the superseded first calibration run:\n  " + "\n  ".join(offenders)
    )


def test_the_allowed_history_files_really_do_frame_it_as_history() -> None:
    """The allowlist is only defensible while those files say which run it was."""
    calibration_readme = _read("benchmarks/calibration/README.md")
    assert "the first row of the table" in calibration_readme
    assert "seeded re-run" in calibration_readme, (
        "the calibration README quotes the first run without pointing at the one that superseded it"
    )


def test_every_surface_stating_the_pass_rates_states_the_measured_ones() -> None:
    """Not merely the absence of the old figures: the presence of the new ones."""
    import json

    results = json.loads(_read("benchmarks/calibration/RESULTS.json"))
    designs = f"{results['design_pass_rate']:.0%}"
    scrambles = f"{results['scramble_pass_rate']:.0%}"

    stating = []
    for path in _calibration_surfaces():
        rel = path.relative_to(ROOT).as_posix()
        if rel in _CALIBRATION_HISTORY_ALLOWED:
            continue
        text = _flat(path.read_text(encoding="utf-8", errors="replace"))
        if WITHDRAWAL_MARKER not in text:
            continue
        if "clear 0.65" not in text and "cleared 0.65" not in text:
            continue
        stating.append(rel)
        missing_rate = [r for r in (designs, scrambles) if r not in text]
        assert not missing_rate, (
            f"{rel} describes the paired control without stating the measured "
            f"rates ({scrambles} of shuffles against {designs} of designs); "
            f"missing {', '.join(missing_rate)}"
        )
        # The claim, not only the figures. "at the same rate" was the first
        # run's finding; the seeded re-run inverted it, and a surface can carry
        # the corrected numbers while still asserting the superseded conclusion
        # in the sentence around them.
        assert "at the same rate" not in text, (
            f"{rel} still says the designs and their shuffles clear the bar at the "
            f"same rate; the artifact measures {scrambles} against {designs}"
        )
    assert stating, "no surface describes the paired control; the sweep found nothing"


# ---------------------------------------------------------------------------
# A table row with the wrong number of cells loses the surplus silently
# ---------------------------------------------------------------------------
def _malformed_table_rows(path: Path) -> list[str]:
    """Rows whose cell count differs from their table's header.

    Markdown renderers drop surplus cells without complaint, so ARCHITECTURE.md
    shipped a competitor table where three rows carried a status column the
    header did not have — and one of those rows was a whole entry pasted in from
    a different table. On the rendered page the extra cells simply vanished, so
    nothing looked wrong and the duplicate was invisible.
    """
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    bad: list[str] = []
    i = 0
    while i < len(lines):
        is_divider = (
            i + 1 < len(lines)
            and lines[i + 1].strip()
            and set(lines[i + 1].replace("|", "").replace(" ", "")) <= set("-:")
        )
        if lines[i].startswith("|") and is_divider:
            header_cells = lines[i].count("|") - 1
            j = i + 2
            while j < len(lines) and lines[j].startswith("|"):
                cells = lines[j].count("|") - 1
                if cells != header_cells:
                    bad.append(
                        f"line {j + 1}: header has {header_cells} cells, row has "
                        f"{cells} — {lines[j][:70]}"
                    )
                j += 1
            i = j
        else:
            i += 1
    return bad


def test_the_table_scan_recognises_a_real_table() -> None:
    """Guards the guard: a parser that matched no tables would pass everywhere."""
    counted = 0
    for path in _shipped_documents():
        if path.suffix != ".md":
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        counted += sum(
            1
            for i, line in enumerate(text.splitlines()[:-1])
            if line.startswith("|")
            and set(text.splitlines()[i + 1].replace("|", "").replace(" ", "")) <= set("-:")
            and text.splitlines()[i + 1].strip()
        )
    assert counted >= 10, f"the scan found only {counted} tables across the docs"


@pytest.mark.parametrize(
    "rel",
    [p.relative_to(ROOT).as_posix() for p in _shipped_documents() if p.suffix == ".md"],
)
def test_no_shipped_table_has_a_row_the_header_cannot_hold(rel: str) -> None:
    bad = _malformed_table_rows(ROOT / rel)

    assert not bad, f"{rel} has table rows the header cannot hold:\n  " + "\n  ".join(bad)
