# SPDX-FileCopyrightText: 2026 Mikhaeel Atef Rizk Wahba
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Guard the repository's public prose against regressing to overclaiming.

The v0.2.1 audit found six classes of defect in text that ships to readers
rather than to an interpreter: a superseded Zenodo *version* DOI cited in
seventeen places, a dead Boltz-2 reference in both bibliographies, a
deposit-ready preprint asserting the software is MIT-licensed when ``LICENSE``
is AGPL-3.0-or-later, an unqualified "the first open-source pipeline" priority
claim, binder-benchmark figures published without the protocol caveat they
need, and three release-metadata files disagreeing about the version number.

None of that is reachable by any other test in this suite, and every one of
those defects is a plain-text substring. These tests are therefore deliberately
string-level and data-driven: the file lists are module constants so a new
document is one line to cover, and the assertions name the exact bad string
that must stay gone and the exact good string that must stay present, so
rewording the surrounding sentence does not break them.

``CHANGELOG.md`` is intentionally outside :data:`PROSE_FILES`: it quotes the old
DOI and the retracted novelty claim verbatim while describing their removal.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]

# --- The exact strings the E-docs fixes turned on ----------------------------

# 10.5281/zenodo.20121496 is the v0.1.0 *version* DOI: an MIT-labelled snapshot
# with neither the benchmarks nor the manuscripts in it. ...495 is the concept
# DOI, which always redirects to the latest archived release.
STALE_VERSION_DOI = "10.5281/zenodo.20121496"
CONCEPT_DOI = "10.5281/zenodo.20121495"

# The Boltz-2 preprint DOI that returns HTTP 404, and the record it moved to.
DEAD_BOLTZ2_DOI = "10.1101/2025.01.20.633574"
LIVE_BOLTZ2_DOI = "10.1101/2025.06.14.659707"

# Licence claims that described bindsight itself as MIT. A bare "MIT" must
# survive in the manuscript: Boltz-2 / BoltzGen really did release weights
# under it, and scrubbing that attribution would be its own misstatement.
MIT_CLAIMS_ABOUT_BINDSIGHT = (
    "MIT-licensed and archived",
    "licensed MIT throughout",
    "(MIT license)",
)

# The retracted, unqualified priority claim, and the hedges that replaced it.
RETRACTED_NOVELTY_CLAIM = re.compile(r"first open[- ]source pipeline", re.IGNORECASE)
PRIORITY_CLAIM = re.compile(r"first open[- ]source", re.IGNORECASE)
NOVELTY_HEDGES = ("as far as we are aware", "to our knowledge")

# The designer benchmark. These constants used to enforce a caveat: the figures
# were produced with ProteinMPNN redesigning the target chain, so every document
# quoting them had to say so. A corrected re-run on a T4 has since superseded
# them, so what has to be enforced is the opposite — the documents must quote the
# corrected figures, and must not present the withdrawn ones as current.
MPNN_CHAIN_FLAG = "--pdb_path_chains"
#: The corrected figures. Any document that publishes the binder result states
#: at least one of them.
BINDER_FIGURES = re.compile(r"0\.88|40\s?%")
#: The withdrawn ones. Permitted only in a sentence that retracts them.
WITHDRAWN_BINDER_FIGURES = re.compile(r"0\.84|50\s?%\s*success|50%")
RETRACTION_WORDS = (
    "withdraw",
    "supersed",
    "earlier run",
    "superseded",
    "corrected",
    "no longer",
    "previous",
)

# --- The documents ------------------------------------------------------------

PROSE_SUFFIXES = frozenset({".md", ".tex", ".bib", ".cff"})
NAMED_PROSE = ("README.md", "SECURITY.md", "CITATION.cff", ".huggingface/README.md")
PROSE_TREES = ("docs", "paper", "benchmarks")

# One bibliography serves both manuscripts; manuscript.tex reaches it via
# \addbibresource{../paper.bib}. The former paper/biorxiv/references.bib
# duplicated 15 of its 18 keys and drifted independently.
BIB_FILES = ("paper/paper.bib",)
MANUSCRIPT_TEX = "paper/biorxiv/manuscript.tex"

# Documents that state, or used to state, a priority claim in prose.
PRIORITY_CLAIM_DOCS = (
    "README.md",
    "docs/index.md",
    "docs/what-is-bindsight.md",
    ".huggingface/README.md",
    "paper/paper.md",
    MANUSCRIPT_TEX,
)

# Documents that quote the pre-fix binder headline figures (ipTM 0.84 /
# 50% success@0.65) and must therefore carry the protocol caveat next to them.
#
# ``docs/results.md`` is generated byte-for-byte by
# ``scripts/build_docs_results.py`` (pinned by
# ``tests/test_docs_results.py::test_generated_page_is_up_to_date``), so the
# caveat has to come from the generator; regenerating the page cannot drop it
# without failing here.
BINDER_FIGURE_DOCS = (
    "README.md",
    "docs/index.md",
    "docs/results.md",
    "ARCHITECTURE.md",
    "CHANGELOG.md",
    "benchmarks/designer_benchmark/RESULTS.md",
    "benchmarks/designer_benchmark/DESIGNER_BENCHMARK.md",
)


def _collect_prose_files() -> list[Path]:
    """Every public text document, resolved from the trees above."""
    files = [ROOT / rel for rel in NAMED_PROSE]
    for tree in PROSE_TREES:
        files.extend(sorted(p for p in (ROOT / tree).rglob("*") if p.suffix in PROSE_SUFFIXES))
    return [p for p in files if p.is_file()]


PROSE_FILES = _collect_prose_files()
PROSE_IDS = [p.relative_to(ROOT).as_posix() for p in PROSE_FILES]


def _read(rel: str | Path) -> str:
    path = rel if isinstance(rel, Path) else ROOT / rel
    return path.read_text(encoding="utf-8")


def _bib_entry(text: str, key: str) -> str:
    """The body of a single BibTeX entry, so a field can be pinned to its key."""
    match = re.search(rf"@\w+\{{{re.escape(key)},(.*?)\n\}}", text, re.DOTALL)
    assert match is not None, f"bibliography entry {key} not found"
    return match.group(1)


# --- Inventory ----------------------------------------------------------------


def test_prose_inventory_resolves_the_public_documents() -> None:
    """Without this, a bad glob would make every scan below vacuously pass."""
    assert len(PROSE_FILES) >= 20
    for expected in (
        "README.md",
        "SECURITY.md",
        "CITATION.cff",
        ".huggingface/README.md",
        "docs/index.md",
        "docs/what-is-bindsight.md",
        "paper/paper.md",
        "paper/paper.bib",
        MANUSCRIPT_TEX,
        "benchmarks/designer_benchmark/RESULTS.md",
    ):
        assert expected in PROSE_IDS, f"not collected: {expected}"


# --- P5: the Zenodo DOI -------------------------------------------------------


@pytest.mark.parametrize("path", PROSE_FILES, ids=PROSE_IDS)
def test_no_public_document_cites_the_superseded_version_doi(path: Path) -> None:
    assert STALE_VERSION_DOI not in _read(path), (
        f"{path.relative_to(ROOT).as_posix()} still cites the v0.1.0 version DOI; "
        f"use the concept DOI {CONCEPT_DOI}"
    )


@pytest.mark.parametrize("rel", ["README.md", "CITATION.cff"])
def test_readme_and_citation_carry_the_concept_doi(rel: str) -> None:
    assert CONCEPT_DOI in _read(rel)


def test_citation_cff_declares_the_concept_doi_as_a_field() -> None:
    """GitHub's "Cite this repository" reads these keys, not the prose."""
    cff = yaml.safe_load(_read("CITATION.cff"))
    assert cff["doi"] == CONCEPT_DOI
    assert any(entry.get("value") == CONCEPT_DOI for entry in cff["identifiers"])


# --- I4: the bibliographies ---------------------------------------------------


@pytest.mark.parametrize("rel", BIB_FILES)
def test_bibliography_replaces_the_dead_boltz2_doi(rel: str) -> None:
    text = _read(rel)
    assert DEAD_BOLTZ2_DOI not in text, f"{rel} still cites the 404ing Boltz-2 DOI"
    assert LIVE_BOLTZ2_DOI in text


@pytest.mark.parametrize("rel", BIB_FILES)
def test_surfacebind_entry_is_balbi_2026(rel: str) -> None:
    """The SURFACE-Bind paper is Balbi et al. 2026, not Khakzad et al. 2025.

    Khakzad is a co-author, not the first author, and the article is dated
    2026. Pin both so the citation cannot drift back.
    """
    entry = _bib_entry(_read(rel), "Balbi2026")
    assert re.search(r"year\s*=\s*\{?\s*2026\s*\}?", entry), entry
    assert "Balbi" in entry, entry
    assert "Khakzad2025" not in _read(rel), "stale Khakzad2025 key still present"


# --- LEGAL: the licence of bindsight itself -----------------------------------


def test_manuscript_no_longer_calls_bindsight_mit_licensed() -> None:
    text = _read(MANUSCRIPT_TEX)
    for claim in MIT_CLAIMS_ABOUT_BINDSIGHT:
        assert claim not in text, f"manuscript still asserts {claim!r} about bindsight"
    assert "AGPL-3.0-or-later" in text


def test_manuscript_keeps_mit_only_as_an_upstream_attribution() -> None:
    """Boltz-2 / BoltzGen weights really are MIT; that sentence must survive.

    The invariant is not "no MIT" but "MIT never names bindsight".
    """
    mit_lines = [line for line in _read(MANUSCRIPT_TEX).splitlines() if "MIT" in line]
    assert mit_lines, "the upstream MIT attribution was scrubbed along with the overclaim"
    for line in mit_lines:
        assert "bindsight" not in line.lower(), line


# --- NOVELTY: the priority claim ----------------------------------------------


@pytest.mark.parametrize("rel", PRIORITY_CLAIM_DOCS)
def test_unqualified_priority_claim_is_gone(rel: str) -> None:
    assert not RETRACTED_NOVELTY_CLAIM.search(_read(rel)), (
        f"{rel} still makes the retracted 'first open-source pipeline' claim"
    )


@pytest.mark.parametrize("rel", PRIORITY_CLAIM_DOCS)
def test_every_surviving_priority_claim_is_hedged(rel: str) -> None:
    """A narrowed claim is still a priority claim; it must carry its qualifier."""
    text = _read(rel)
    for match in PRIORITY_CLAIM.finditer(text):
        window = text[max(0, match.start() - 400) : match.end() + 400].lower()
        assert any(hedge in window for hedge in NOVELTY_HEDGES), (
            f"{rel} claims priority at offset {match.start()} without a hedge"
        )


def test_readme_headline_hedges_the_priority_claim() -> None:
    """The hedge sits in the lede itself, not further down the page."""
    lede = "\n".join(_read("README.md").splitlines()[:12])
    assert "as far as we are aware, the first open-source tool" in lede
    assert "both halves end-to-end" in lede


# --- BINDER-BENCHMARK: provenance of the headline figures ---------------------


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_binder_figures_are_quoted_in_these_documents(rel: str) -> None:
    """Pins the list below to documents that really do publish the figures."""
    assert BINDER_FIGURES.search(_read(rel)), f"{rel} no longer quotes 0.88 / 40%"


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_the_withdrawn_figures_are_never_presented_as_current(rel: str) -> None:
    """ipTM 0.84 and 50% success@0.65 came from the pre-fix protocol.

    That run invoked ProteinMPNN without ``--pdb_path_chains``, so it redesigned
    the ERBB2 target chain along with the binder: the designs were optimised
    against a partly-invented surface and then scored against the native one. A
    corrected re-run on a T4 supersedes them.

    These tests used to enforce the caveat. Now they enforce the retraction: the
    old numbers may appear only in a sentence that withdraws them, because a
    document that prints both sets without saying which is current publishes two
    results.
    """
    text = _read(rel)
    for match in WITHDRAWN_BINDER_FIGURES.finditer(text):
        window = text[max(0, match.start() - 500) : match.end() + 500].lower()
        assert any(word in window for word in RETRACTION_WORDS), (
            f"{rel} prints a withdrawn binder figure at offset {match.start()} "
            "without retracting it"
        )


@pytest.mark.parametrize("rel", BINDER_FIGURE_DOCS)
def test_the_corrected_protocol_is_named_where_the_figures_appear(rel: str) -> None:
    """The claim that makes the new figures trustworthy must travel with them.

    "The target was held fixed" is the whole difference between this run and the
    superseded one, and it is checkable: every design carries a target chain
    byte-identical to the native domain IV.
    """
    text = _read(rel)
    assert MPNN_CHAIN_FLAG in text or "target chain" in text.lower(), (
        f"{rel} quotes the binder figures without saying the target was held fixed"
    )


# --- Release metadata coherence -----------------------------------------------


def test_version_agrees_across_pyproject_citation_and_zenodo() -> None:
    """``bindsight --version``, the citation and the deposit must not disagree."""
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]["version"]
    citation = str(yaml.safe_load(_read("CITATION.cff"))["version"])
    zenodo = json.loads(_read(".zenodo.json"))["version"].removeprefix("v")
    assert re.fullmatch(r"\d+\.\d+\.\d+", pyproject), pyproject
    assert citation == pyproject, f"CITATION.cff {citation} != pyproject {pyproject}"
    assert zenodo == pyproject, f".zenodo.json {zenodo} != pyproject {pyproject}"


def test_licence_agrees_across_pyproject_citation_and_zenodo() -> None:
    """The v0.1.0 Zenodo record said MIT for AGPL code; that is what to prevent."""
    pyproject = tomllib.loads(_read("pyproject.toml"))["project"]["license"]
    citation = yaml.safe_load(_read("CITATION.cff"))["license"]
    zenodo = json.loads(_read(".zenodo.json"))["license"]
    assert pyproject == "AGPL-3.0-or-later"
    assert citation == pyproject
    assert zenodo == pyproject


# ---------------------------------------------------------------------------
# The manuscripts must not out-claim the README
# ---------------------------------------------------------------------------
#: Backends the README states have not been run end to end, with the words it
#: uses to say so. A manuscript may name them; it may not present them as
#: demonstrated.
UNEXECUTED_BACKENDS = ("Modal", "Colab")

#: Words that turn a mention into a disclosure rather than a claim.
_HEDGES = (
    "not been run",
    "not executed",
    "not yet",
    "prepared",
    "demonstration",
    "demo",
    "needs a human",
    "does not permit",
    "cannot",
    "implemented but",
)

MANUSCRIPTS = ("paper/paper.md", "paper/validation/manuscript.md")


@pytest.mark.parametrize("rel", MANUSCRIPTS)
@pytest.mark.parametrize("backend", UNEXECUTED_BACKENDS)
def test_no_manuscript_presents_an_unexecuted_backend_as_demonstrated(
    rel: str, backend: str
) -> None:
    """paper.md claimed the GPU half runs end-to-end on Colab, Modal and Docker.

    The README calls Modal "Prepared, not executed" and Colab "a demo, not a
    reproducibility path". Both documents shipped, contradicting each other,
    and nothing compared them — a reviewer reading the pair is the first person
    who would have.
    """
    path = ROOT / rel
    if not path.is_file():
        pytest.skip(f"{rel} not present")
    text = path.read_text(encoding="utf-8")
    # Scoped to the paragraph, not a character window: a qualification belongs
    # to the sentence it qualifies, and a fixed radius either clips a hedge that
    # is genuinely present or reaches into unrelated prose.
    for para in re.split(r"\n\s*\n", text):
        low = para.lower()
        if backend.lower() not in low or not re.search(r"end[- ]to[- ]end", low):
            continue
        assert any(h in low for h in _HEDGES), (
            f"{rel} presents {backend} as running end to end, but the README "
            f"states it has not been run that way. Paragraph:\n{para[:400]}"
        )


def test_the_readme_still_marks_those_backends_unexecuted() -> None:
    """If a backend is genuinely demonstrated, this pair of tests must be revised
    together rather than the manuscript quietly getting ahead of the evidence."""
    readme = _read("README.md").lower()
    assert "prepared, not executed" in readme
    assert "not a reproducibility path" in readme


def test_the_stated_test_count_does_not_exceed_the_suite() -> None:
    """The manuscript claimed 635 tests against a suite of 784 functions.

    Stated as a floor rather than an exact count, so adding tests does not make
    the paper wrong, and checked against a static count of test functions —
    which is a lower bound on collected cases, so a claim that passes here is
    true of the real suite too.
    """
    text = _read("paper/paper.md")
    match = re.search(r"over (\d[\d,]*) unit and integration tests", text)
    assert match, "paper.md no longer states a test count in the expected form"
    claimed = int(match.group(1).replace(",", ""))
    functions = sum(
        len(re.findall(r"^\s*(?:async )?def test_", p.read_text(encoding="utf-8"), re.M))
        for p in (ROOT / "tests").glob("*.py")
    )
    assert claimed <= functions, (
        f"paper.md claims over {claimed} tests; only {functions} test functions exist"
    )


#: Designers and validators that no shipped backend can execute. The README's
#: runner-and-plugin table is the authority; these must never be ticked off as
#: delivered elsewhere.
UNEXECUTED_PLUGINS = ("BindCraft", "BoltzGen", "Chai-1r", "AF2-IG")


@pytest.mark.parametrize("plugin", UNEXECUTED_PLUGINS)
def test_no_completed_checklist_item_claims_an_unexecuted_plugin(plugin: str) -> None:
    """`- [x] design/ RFdiffusion+ProteinMPNN (+ BindCraft, BoltzGen)` read as
    delivered while the same document's table said those two had never run.

    A checklist is the fastest thing in a design document to scan and the
    easiest to leave behind, so the tick is the claim that matters.
    """
    # A tick about a plugin's *licence* or citation is not a delivery claim, and
    # confirming BindCraft's licence is genuinely done.
    not_about_running = ("licen", "cite", "citation", "attribut")
    for line in _read("ARCHITECTURE.md").splitlines():
        low = line.lower()
        if not line.lstrip().startswith("- [x]"):
            continue
        if any(word in low for word in not_about_running):
            continue
        assert plugin.lower() not in low, (
            f"ARCHITECTURE.md ticks off {plugin}, which no backend can run:\n{line}"
        )


def test_the_three_way_benchmark_is_not_claimed_as_a_mitigation_in_place() -> None:
    """It was written as a mitigation already taken; it is deferred work.

    BindCraft and BoltzGen have never executed, so a benchmark comparing all
    three designers cannot have been run.
    """
    text = _read("ARCHITECTURE.md").lower()
    assert "benchmark all three in the paper" not in text


def test_the_readme_still_marks_those_plugins_unexecuted() -> None:
    """The anchor for the two tests above: if this changes, revise them together.

    "implemented, not yet executed" was the original phrasing and was too kind —
    it implies the plugins would work if someone ran them, when no backend
    builds an environment in which the dispatch can succeed. Either wording
    keeps the manuscripts honest, which is what these tests are for.
    """
    readme = _read("README.md")
    assert any(
        phrase in readme
        for phrase in (
            "implemented, not yet executed",
            "not runnable",
            "no shipped backend can run them",
        )
    )
