"""Kaggle Notebooks GPU runner.

Drives Kaggle's free GPU tier (T4×2, ~30 GPU-hr/week) headlessly via the Kaggle
public API: push a generated kernel that runs :mod:`bindsight.runners.job_exec`,
poll its status, then pull the results tarball from the kernel output. Requires
the ``runners`` extra (``kaggle``) and Kaggle API credentials
(``~/.kaggle/kaggle.json`` or ``KAGGLE_USERNAME``/``KAGGLE_KEY``).

The ``kaggle`` client is imported lazily so ``import bindsight`` works without
the extra installed.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from bindsight.cost import estimate
from bindsight.runners.protocol import CostEstimate, JobHandle, JobStatus

LOG = logging.getLogger(__name__)


def _require_kaggle() -> Any:
    """Import + authenticate the Kaggle API, with a clear error if missing."""
    try:
        from kaggle.api.kaggle_api_extended import KaggleApi
    except ImportError as e:
        raise RuntimeError(
            'Kaggle runner needs the "runners" extra: pip install -e ".[runners]" '
            "and Kaggle credentials (~/.kaggle/kaggle.json)."
        ) from e
    api = KaggleApi()
    api.authenticate()
    return api


_KERNEL_TEMPLATE = """\
# Auto-generated by bindsight KaggleRunner — runs the design+validation executor.
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "bindsight"], check=True)
subprocess.run(
    [sys.executable, "-m", "bindsight.runners.job_exec",
     "/kaggle/input/{dataset}/spec.json", "/kaggle/working/{handle_id}.tar.gz"],
    check=True,
)
"""


class KaggleRunner:
    """Headless Kaggle Notebooks runner (push kernel, poll, pull tarball)."""

    name = "kaggle"

    def __init__(
        self,
        *,
        designer: str = "rfdiff_mpnn",
        gpu_type: str = "T4",
        username: str | None = None,
        poll_interval_s: int = 30,
    ) -> None:
        self.designer = designer
        self.gpu_type = gpu_type
        self.username = username
        self.poll_interval_s = poll_interval_s

    def estimate_cost(self, spec_size: int) -> CostEstimate:
        """Estimate cost (free tier — $0, but queue/quota limited)."""
        return estimate(
            backend=self.name,
            stage="design",
            plugin=self.designer,
            n_units=spec_size,
            gpu_type=self.gpu_type,
        )

    def submit(self, spec_path: Path, *, results_dir: Path) -> JobHandle:
        """Push a Kaggle kernel that runs the executor on the spec."""
        api = _require_kaggle()
        results_dir.mkdir(parents=True, exist_ok=True)
        handle_id = uuid.uuid4().hex[:12]
        user = self.username or api.config_values.get("username", "user")

        work = results_dir / f"kaggle_{handle_id}"
        work.mkdir(parents=True, exist_ok=True)
        slug = f"bindsight-{handle_id}"
        (work / "kernel.py").write_text(
            _KERNEL_TEMPLATE.format(dataset=slug, handle_id=handle_id)
        )
        (work / "kernel-metadata.json").write_text(
            json.dumps(
                {
                    "id": f"{user}/{slug}",
                    "title": slug,
                    "code_file": "kernel.py",
                    "language": "python",
                    "kernel_type": "script",
                    "enable_gpu": True,
                    "enable_internet": True,
                    "dataset_sources": [f"{user}/{slug}"],
                }
            )
        )
        # Ship the spec + target structure as a dataset the kernel reads.
        for f in spec_path.parent.iterdir():
            (work / f.name).write_bytes(f.read_bytes()) if f.is_file() else None
        api.kernels_push(str(work))
        LOG.info("kaggle: pushed kernel %s/%s", user, slug)
        return JobHandle(
            backend=self.name,
            id=f"{user}/{slug}",
            submitted_at=datetime.now(UTC).isoformat(timespec="seconds"),
            results_dir=str(results_dir),
            handle_id=handle_id,
        )

    def poll(self, handle: JobHandle) -> JobStatus:
        """Query the kernel's run status."""
        api = _require_kaggle()
        status = api.kernels_status(handle.id)
        s = str(status.get("status", "")).lower() if isinstance(status, dict) else str(status).lower()
        mapping = {
            "queued": "queued",
            "running": "running",
            "complete": "succeeded",
            "error": "failed",
            "cancelacknowledged": "cancelled",
        }
        return JobStatus(handle=handle, state=mapping.get(s, "running"), log_tail=s)

    def fetch(self, handle: JobHandle) -> Path:
        """Block until the kernel completes; download the results tarball."""
        api = _require_kaggle()
        results_dir = Path(getattr(handle, "results_dir", "."))
        handle_id = getattr(handle, "handle_id", "")
        while True:
            st = self.poll(handle)
            if st.state in {"succeeded", "failed", "cancelled"}:
                break
            time.sleep(self.poll_interval_s)
        if st.state != "succeeded":
            raise RuntimeError(f"kaggle kernel {handle.id} finished in state {st.state}")
        api.kernels_output(handle.id, str(results_dir))
        tarball = results_dir / f"{handle_id}.tar.gz"
        if not tarball.exists():
            raise RuntimeError(f"kaggle kernel {handle.id} produced no tarball at {tarball}")
        return tarball


__all__ = ["KaggleRunner"]
