"""Builder for the self-contained Kaggle kernel that runs the design+validation job.

Kaggle's free GPU is a **Tesla P100 (sm_60)** whose preinstalled stack
(py3.12 / torch 2.10+cu128) supports neither the P100 chip nor RFdiffusion's
legacy requirements. RFdiffusion (the only designer that fits 16 GB) needs an old
py3.9 / torch-1.12 environment, and that environment is mutually exclusive with
the modern Boltz-2 validator (torch ≥2.2 / py ≥3.10). So the kernel builds **two
micromamba environments** on the P100 and runs the existing executor
(:mod:`bindsight.runners.job_exec`) across them:

- ``se3``  (py3.9, torch 1.12.1+cu113 — supports sm_60): RFdiffusion + ProteinMPNN.
- ``boltz`` (py3.11, torch 2.2.2+cu118 — still ships sm_60): Boltz-2 + bindsight.

``job_exec`` runs under ``boltz`` and invokes the design tools with the ``se3``
interpreter via ``BINDSIGHT_DESIGN_PYTHON`` (a wrapper that does ``micromamba run
-p .../se3``), so there is still exactly one executor — only the per-tool
interpreter differs. The design spec + target structure are embedded as base64
(no Kaggle dataset needed); the results tarball is written to
``/kaggle/working/<handle_id>.tar.gz`` for :meth:`KaggleRunner.fetch`.

The pinned upstream revisions come from :mod:`bindsight.runners.tools` so the
kernel can never drift from the Colab/Modal/local paths.
"""

from __future__ import annotations

from typing import Any

from bindsight.runners import tools

# Channels-free pip recipe for RFdiffusion's legacy env. RFdiffusion's own
# env/SE3nv.yml pins pytorch=1.9/cudatoolkit=11.1 via conda channels whose ancient
# builds are unreliable to solve today; the cu113 pip wheels below are the
# community-proven equivalent and (unlike Kaggle's default cu128 torch) include the
# P100's sm_60 kernels. SE3-Transformer's own requirements (e3nn==0.3.3, dllogger,
# …) come from RFdiffusion/env/SE3Transformer/requirements.txt at install time.
# cu113 is the newest CUDA wheel line for torch 1.12.1; the dgl cu113 wheels at the
# find-links below are therefore built against this exact torch. Package name is
# plain ``dgl`` with a ``+cu113`` local version (the old ``dgl-cu113`` name is gone).
_SE3_TORCH = "torch==1.12.1+cu113"
_SE3_TORCH_INDEX = "https://download.pytorch.org/whl/cu113"
_SE3_DGL = "dgl==1.0.2+cu113"
_SE3_DGL_FIND = "https://data.dgl.ai/wheels/cu113/repo.html"
_SE3_EXTRA_PIP = [
    "hydra-core==1.3.2",
    "pyrsistent",
    "omegaconf",
    "icecream",
    "scipy",
    "numpy<1.24",
    "opt_einsum",
    "opt_einsum_fx",
    "e3nn==0.3.3",
]
# Boltz-2 env: a torch that still ships sm_60 (Kaggle's default cu128 does not).
_BOLTZ_TORCH = "torch==2.2.2"
_BOLTZ_TORCH_INDEX = "https://download.pytorch.org/whl/cu118"


_BINDSIGHT_REPO = "https://github.com/mikhaeelatefrizk/bindsight.git"


def build_kernel_script(
    *,
    handle_id: str,
    payload: dict[str, str],
    bindsight_ref: str | None = None,
    n_trajectories_note: int | None = None,
) -> str:
    """Return the full Python source of the Kaggle kernel.

    Args:
        handle_id: stable id; the results tarball is ``<handle_id>.tar.gz``.
        payload: ``{filename: base64}`` for the spec dir (``spec.json`` + the
            target structure file the spec references).
        bindsight_ref: optional git ref (branch/tag/sha) to install bindsight from;
            defaults to the repository's default branch. Used to run a feature
            branch before it is merged.
        n_trajectories_note: optional, embedded only as a log breadcrumb.
    """
    git_url = f"git+{_BINDSIGHT_REPO}" + (f"@{bindsight_ref}" if bindsight_ref else "")
    # Emit Python *literals* with repr(), not json.dumps() — JSON's null/true/false
    # are not valid Python identifiers (an early bug embedded ``= null``).
    consts = {
        "HANDLE_ID": handle_id,
        "PAYLOAD": payload,
        "N_TRAJ_NOTE": n_trajectories_note,
        "RFDIFF_REPO": tools.RFDIFF_REPO,
        "RFDIFF_COMMIT": tools.RFDIFF_COMMIT,
        "RFDIFF_WEIGHTS": tools.RFDIFF_WEIGHTS,
        "MPNN_REPO": tools.PROTEINMPNN_REPO,
        "MPNN_COMMIT": tools.PROTEINMPNN_COMMIT,
        "BOLTZ_PIP": tools.BOLTZ_PIP,
        "SE3_TORCH": _SE3_TORCH,
        "SE3_TORCH_INDEX": _SE3_TORCH_INDEX,
        "SE3_DGL": _SE3_DGL,
        "SE3_DGL_FIND": _SE3_DGL_FIND,
        "SE3_EXTRA_PIP": _SE3_EXTRA_PIP,
        "BOLTZ_TORCH": _BOLTZ_TORCH,
        "BOLTZ_TORCH_INDEX": _BOLTZ_TORCH_INDEX,
        "BINDSIGHT_GIT": git_url,
    }
    header_lines = ["# Auto-generated by bindsight KaggleRunner — split-env design+validation."]
    header_lines += [f"{name} = {value!r}" for name, value in consts.items()]
    return "\n".join(header_lines) + "\n\n" + _BODY


def build_kernel_metadata(*, username: str, slug: str) -> dict[str, Any]:
    """kernel-metadata.json for a GPU + internet script kernel (no dataset sources)."""
    return {
        "id": f"{username}/{slug}",
        "title": slug,
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }


# The static kernel body. References the variables defined in the generated header
# above; kept brace-safe (no .format) so the embedded shell/Python is verbatim.
_BODY = r'''
import base64, json, os, pathlib, subprocess, sys, time

MR = "/opt/mamba"                       # MAMBA_ROOT_PREFIX (off the /kaggle/working output volume)
MM = "/opt/micromamba/bin/micromamba"
TOOLS = "/opt/tools"
SE3 = f"{MR}/envs/se3"
BOLTZ = f"{MR}/envs/boltz"
os.environ["MAMBA_ROOT_PREFIX"] = MR


def sh(cmd, env=None):
    """Run a shell command, streaming output; raise on non-zero exit."""
    print(f"\n+ {cmd}", flush=True)
    t0 = time.time()
    r = subprocess.run(cmd, shell=True, env={**os.environ, **(env or {})})
    print(f"  ({time.time()-t0:.0f}s, exit={r.returncode})", flush=True)
    if r.returncode != 0:
        raise SystemExit(f"step failed: {cmd}")


def step(msg):
    print(f"\n========== {msg} ==========", flush=True)


step("GPU check")
sh("nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader || true")

step("install micromamba")
pathlib.Path("/opt/micromamba/bin").mkdir(parents=True, exist_ok=True)
sh("curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest "
   "| tar -xj -C /opt/micromamba bin/micromamba")
sh(f"{MM} --version")

step("clone RFdiffusion + ProteinMPNN, fetch weights")
pathlib.Path(TOOLS).mkdir(parents=True, exist_ok=True)
if not pathlib.Path(f"{TOOLS}/RFdiffusion").exists():
    sh(f"git clone -q {RFDIFF_REPO} {TOOLS}/RFdiffusion")
    sh(f"git -C {TOOLS}/RFdiffusion checkout -q {RFDIFF_COMMIT}")
pathlib.Path(f"{TOOLS}/RFdiffusion/models").mkdir(parents=True, exist_ok=True)
for name, url in RFDIFF_WEIGHTS.items():
    dst = f"{TOOLS}/RFdiffusion/models/{name}"
    if not pathlib.Path(dst).exists():
        sh(f"wget -q '{url}' -O '{dst}'")
if not pathlib.Path(f"{TOOLS}/ProteinMPNN").exists():
    sh(f"git clone -q {MPNN_REPO} {TOOLS}/ProteinMPNN")
    sh(f"git -C {TOOLS}/ProteinMPNN checkout -q {MPNN_COMMIT}")

step("build se3 env (RFdiffusion: py3.9 / torch1.12+cu113 — sm_60 capable)")
sh(f"{MM} create -y -p {SE3} -c conda-forge python=3.9 pip")
sh(f"{MM} run -p {SE3} pip install -q --no-input {SE3_TORCH} --extra-index-url {SE3_TORCH_INDEX}")
sh(f"{MM} run -p {SE3} pip install -q --no-input {SE3_DGL} -f {SE3_DGL_FIND}")
sh(f"{MM} run -p {SE3} pip install -q --no-input " + " ".join(f"'{p}'" for p in SE3_EXTRA_PIP))
# SE3-Transformer's own requirements (e3nn pin, dllogger, …), then the packages.
sh(f"{MM} run -p {SE3} pip install -q --no-input -r {TOOLS}/RFdiffusion/env/SE3Transformer/requirements.txt")
sh(f"{MM} run -p {SE3} pip install -q --no-input --no-deps {TOOLS}/RFdiffusion/env/SE3Transformer")
sh(f"{MM} run -p {SE3} pip install -q --no-input --no-deps -e {TOOLS}/RFdiffusion")
# Sanity: RFdiffusion importable + CUDA usable on the P100 in this env.
sh(f"{MM} run -p {SE3} python -c \""
   "import torch, dgl, e3nn; "
   "print('se3 torch', torch.__version__, 'cuda', torch.cuda.is_available(), "
   "torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NO-CUDA'); "
   "x=torch.zeros(4,device='cuda'); print('se3 cuda op ok', (x+1).sum().item())\"")

step("build boltz env (Boltz-2 + bindsight: py3.11 / torch2.2+cu118 — sm_60 capable)")
sh(f"{MM} create -y -p {BOLTZ} -c conda-forge python=3.11 pip")
sh(f"{MM} run -p {BOLTZ} pip install -q --no-input {BOLTZ_TORCH} --index-url {BOLTZ_TORCH_INDEX}")
sh(f"{MM} run -p {BOLTZ} pip install -q --no-input '{BOLTZ_PIP}' biopython {BINDSIGHT_GIT}")
sh(f"{MM} run -p {BOLTZ} python -c \""
   "import torch; print('boltz torch', torch.__version__, 'cuda', torch.cuda.is_available(), "
   "torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NO-CUDA'); "
   "x=torch.zeros(4,device='cuda'); print('boltz cuda op ok', (x+1).sum().item())\"")

step("write se3 interpreter wrapper")
wrapper = "/opt/se3_python.sh"
pathlib.Path(wrapper).write_text(
    "#!/bin/bash\n"
    f"export MAMBA_ROOT_PREFIX={MR}\n"
    f"exec {MM} run -p {SE3} python \"$@\"\n"
)
os.chmod(wrapper, 0o755)

step("materialise spec + target structure (embedded base64)")
spec_dir = pathlib.Path("/tmp/spec"); spec_dir.mkdir(parents=True, exist_ok=True)
for name, b64 in PAYLOAD.items():
    (spec_dir / name).write_bytes(base64.b64decode(b64))
    print("  wrote", name, (spec_dir / name).stat().st_size, "bytes")
print("  spec:", (spec_dir / "spec.json").read_text()[:400])

step("run job_exec (RFdiffusion -> ProteinMPNN under se3; Boltz-2 + orchestration under boltz)")
out_tmp = f"/tmp/{HANDLE_ID}.tar.gz"
job_env = {
    "BINDSIGHT_TOOLS_ROOT": TOOLS,
    "BINDSIGHT_DESIGN_PYTHON": wrapper,
}
sh(f"{MM} run -p {BOLTZ} python -m bindsight.runners.job_exec "
   f"{spec_dir}/spec.json {out_tmp}", env=job_env)

step("stage tarball to /kaggle/working (keep the output volume lean)")
pathlib.Path("/kaggle/working").mkdir(parents=True, exist_ok=True)
sh(f"cp {out_tmp} /kaggle/working/{HANDLE_ID}.tar.gz")
sz = pathlib.Path(f"/kaggle/working/{HANDLE_ID}.tar.gz").stat().st_size
print(f"\nDONE -> /kaggle/working/{HANDLE_ID}.tar.gz ({sz/1e6:.2f} MB)")
'''
