#!/usr/bin/env python
# SPDX-FileCopyrightText: 2026 Mikhaeel Atef Rizk Wahba
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Regenerate the surfaceome Ensembl-gene map from UniProt.

    python scripts/build_surfy_gene_map.py

The surfaceome reference is a list of UniProt accessions, but a differential
expression table is keyed by Ensembl gene id. Without a mapping between them,
"the eligible surfaceome" can only be approximated by whichever genes the
pipeline happened to resolve during a run — which is the enriched subset, not
the surfaceome. Any rank taken within that subset is then a rank within the
pipeline's own output rather than within the set it should be judged against.

This script resolves the mapping once, from the UniProt cross-reference for
every reviewed human protein, and vendors the result so no run needs the
network for it. It writes ``bindsight/surfaceome/data/surfy_v1.ensembl.tsv``.

Run it when the surfaceome list changes. The output is committed.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "bindsight" / "surfaceome" / "data"
ACCESSIONS = DATA_DIR / "surfy_v1.uniprot.txt"
OUT = DATA_DIR / "surfy_v1.ensembl.tsv"

UNIPROT_STREAM = (
    "https://rest.uniprot.org/uniprotkb/stream"
    "?query=reviewed:true%20AND%20organism_id:9606"
    "&fields=accession,xref_ensembl&format=json"
)


def fetch_human_gene_ids(url: str = UNIPROT_STREAM) -> dict[str, set[str]]:
    """Accession -> Ensembl gene ids, for every reviewed human protein.

    The TSV form of this query returns transcript ids, not gene ids, so the JSON
    form is used and the ``GeneId`` cross-reference property is read directly.
    """
    print(f"fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=600) as response:
        payload = json.load(response)

    mapping: dict[str, set[str]] = {}
    for entry in payload.get("results", []):
        accession = entry.get("primaryAccession")
        if not accession:
            continue
        genes: set[str] = set()
        for xref in entry.get("uniProtKBCrossReferences", []):
            if xref.get("database") != "Ensembl":
                continue
            for prop in xref.get("properties", []):
                if prop.get("key") == "GeneId" and prop.get("value"):
                    # Strip the version suffix; GDC counts are keyed unversioned.
                    genes.add(str(prop["value"]).split(".")[0])
        if genes:
            mapping[accession] = genes
    print(f"resolved {len(mapping)} accessions to at least one gene", file=sys.stderr)
    return mapping


def main() -> int:
    """Build and write the map."""
    if not ACCESSIONS.exists():
        print(f"missing {ACCESSIONS}", file=sys.stderr)
        return 1
    # Use the package's own parser. The file carries a comment header, and a
    # naive whitespace split silently turns its prose into fake accessions —
    # which inflates the surfaceome and quietly corrupts anything counted over it.
    sys.path.insert(0, str(REPO_ROOT))
    from bindsight.surfaceome.surfy import _parse_accessions

    surfaceome = set(_parse_accessions(ACCESSIONS.read_text(encoding="utf-8")))
    mapping = fetch_human_gene_ids()

    rows: list[tuple[str, str]] = []
    unresolved: list[str] = []
    for accession in sorted(surfaceome):
        genes = mapping.get(accession)
        if not genes:
            unresolved.append(accession)
            continue
        rows.extend((gene, accession) for gene in sorted(genes))

    header = (
        "# Ensembl gene id -> UniProt accession, for the SURFY surfaceome.\n"
        "# Generated by scripts/build_surfy_gene_map.py from the UniProt\n"
        "# cross-references of reviewed human proteins. Versionless gene ids,\n"
        "# matching how GDC STAR-Counts tables are keyed.\n"
        f"# {len(rows)} pairs covering {len(surfaceome) - len(unresolved)}"
        f" of {len(surfaceome)} accessions.\n"
    )
    OUT.write_text(
        header + "\n".join(f"{g}\t{a}" for g, a in rows) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"wrote {OUT}: {len(rows)} pairs", file=sys.stderr)
    if unresolved:
        # Named rather than hidden: an accession with no gene id can never be
        # matched to a counts table, and that is a coverage fact worth knowing.
        print(
            f"{len(unresolved)} accession(s) have no Ensembl gene cross-reference: "
            f"{', '.join(unresolved[:10])}{'...' if len(unresolved) > 10 else ''}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
